// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGORqzjHvZIgWJbw31dl3IUCz_zlKrrV4',
    appId: '1:604714705615:web:c68eab300db55aa7fa0dba',
    messagingSenderId: '604714705615',
    projectId: 'socail-media-9a4e0',
    authDomain: 'socail-media-9a4e0.firebaseapp.com',
    storageBucket: 'socail-media-9a4e0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHdEcxRllIA_LpY8JpOd1WGZboM-CBK-M',
    appId: '1:604714705615:android:656195c991adab44fa0dba',
    messagingSenderId: '604714705615',
    projectId: 'socail-media-9a4e0',
    storageBucket: 'socail-media-9a4e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVb2XIa2qbjkHabto5G6qB9bAwqpDc_6o',
    appId: '1:604714705615:ios:2c2912768cfebc61fa0dba',
    messagingSenderId: '604714705615',
    projectId: 'socail-media-9a4e0',
    storageBucket: 'socail-media-9a4e0.appspot.com',
    iosBundleId: 'com.example.socialMedia',
  );
}
